# ./docker-compose.yml

version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_web

    volumes:
      - ./src/:/var/www/html/
    ports:
      - "8000:80"

    stdin_open: true
    tty: true
